name: Docker Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
  release:
    types: [released]

jobs:
  base:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      tag-prefix: ""
      php-variation: base
      checkout-type: branch
    secrets: inherit
